version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: my-rest-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_CNN=mongodb://mongo:27017/api-rest
      - JWT_SECRET=T3stN0d3jS13*
      - GOOGLE_API_KEY=AIzaSyBNSdXr282nzMlw3qvZJiqeDgrBSOwpw4c
    depends_on:
      - mongo

volumes:
  mongo-data:
